[project]
name = "juomaripro-app"
version = "0.1.0"
description = "Finds cheap prices and lists them."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "selenium>=4.35.0",
]

[dependency-groups]
dev = [
    "flake8>=7.3.0",
]
